let gites = {
  lodge: {
    name: "The Lodge",
    size: "2 Double Ensuite Bedrooms",
    folder: "lodge",
    image: "hero_lodge_1920px",
    content:
      "The Lodge is a luxury rental property that offers guests two beautifully designed double ensuite bedrooms. Each bedroom is spacious and boasts high-quality bedding and goose feather pillows, with shower products provided in all bathrooms. The Lodge features underfloor heating and cooling, and all the bedrooms are equipped with a TV/DVD with international channels, as well as Wi-Fi access both inside and in the garden. \n \n The first bedroom is themed in a Steampunk style, and is air-conditioned with a super-king sized bed. This room also features a double sink unit, large walk-in shower, and illuminated mirrors. The second bedroom is themed as yet to be announced, and is located on the ground floor with a queen sized bed and underfloor heating. This room also features a vanity unit, large wet room shower, and illuminated mirrors.The Lodge's kitchen is fully equipped with a range cooker, dishwasher, fridge/freezer, espresso maker, and more. The kitchen features stone worktops and plenty of space for guests to prepare their favorite dishes. A washer/dryer is also available in a separate laundry area. \n \n The lodge's outdoor space is beautifully landscaped with a private heated saltwater plunge pool, a gazebo with high-quality dining table, a sunbathing area with chaise longues, a barbeque, and views of the forest and stunning sunsets to the west. The garden also features night time mood lighting, making it an ideal place to relax and enjoy the beautiful surroundings.",
    information: {
      facilities: [
        "All en-suite bedrooms (Air-conditioning to 1st floor)",
        "High quality cotton bedding with goose feather pillows (made up when you arrive)",
        "Toiletries (shampoo/bodywash) provided in all bathrooms",
        "Welcome pack to get you up and running",
        "Dining/breakfast table",
        "International power adapters",
        "Numeric code valuables safe",
        "Bose bluetooth speaker",
        "Underfloor heating (and cooling)",
        "Super-king or queen sized beds",
        "43”/108cm flat-screen TV with internet/international channels",
        "WiFi (Inside and in the garden)",
        "Pool towels",
      ],
      suites: [
        {
          theme: "Steampunk Theme",
          facilities: [
            "1st floor / 21m2",
            "Super-king / 180cm bed",
            "Air-conditioned",
            "High-quality duvet, pillows and bed linen",
            "Oak furniture including wardrobe, chest of drawers and custom, steam-punk bedside tables",
            "Clock radio with wireless/wired charging/USB",
            "Blackout curtains",
            "Hairdryer",
            "Double sink unit with lots of storage",
            "Large walk-in shower with wall-mounted shampoo/body-wash dispensers",
            "Illuminated magnifying mirror",
            "Large heated and illuminated mirror",
          ],
        },
        {
          theme: "TBA Theme",
          facilities: [
            "Ground floor / 16m2",
            "Queen / 160cm bed",
            "Underfloor heating (and cooling)",
            "High-quality duvet, pillows and bed linen",
            "Solid oak bedroom suite",
            "Clock radio with wireless/wired charging/USB",
            "Blackout curtains",
            "Hairdryer",
            "Vanity unit with lots of storage",
            "High quality towels including large bath sheet",
            "Heated towel rail",
            "Large, walk-in wet room shower with wall-mounted shampoo/body-wash dispensers",
            "Illuminated mirror",
            "Illuminated magnifying mirror",
          ],
        },
      ],
      kitchen: {
        information:
          "The Lodge is fitted with a delightful kitchen featuring stone worktops and plenty of space for preparing your favourite dishes.  It is very well equipped with quality aplliances and all the necessities for your stay including:",
        facilities: [
          "Falcon Kitchener Range cooker with extractor hood",
          "Bosch Dishwasher",
          "Whirlpool Fridge/Freezer",
          "Bosch Espresso coffee maker",
          "Kettle",
          "Microwave",
          "Electric juice maker",
          "Electric whisk",
          "Cafetiere",
          "Toaster",
          "A wide selection of cutlery, glasses, utensils and Denby crockery",
          "A Washer/dryer is available in a separate laundry area",
        ],
      },
      garden: [
        "Landscaped garden with night time mood lighting",
        "Private, heated, Salt water plunge pool",
        "Gazebo with high-quality dining table and chairs/cushions (for 6).  Remote control mood/dining lighting",
        "Terrace/sunbathing area with chaises longues/cushions",
        "Barbeque",
        "Views to the forest and stunning sunsets to the west!",
      ],
    },
    images: ["lodge-bedroom-area", "hero_lodge_1920px", "lodge-bedroom-area-2", "hero_lodge_1920px-2"],
  },
  barn: {
    name: "The Barn",
    size: "3 Double Ensuite Bedrooms",
    folder: "barn",
    image: "barn-bedroom-area",
    content:
      "The Barn has been created from one of the original, stone wine tanks) when the property was purchased. A new roof (with lots of insulation) was installed in 2021, along with completely new and heavily insulated floors, now covered in natural travertine with the stone structure being retained, renovated and repointed. A first floor was installed during the renovation with all the structural timberwork being hand-made on-site from French oak. The renovation works posed its own set of challenges, starting with the fact that none of the walls were straight or vertical!<br /><br />The main entrance to the Barn is via the sheltered courtyard adjacent to the gravelled parking and the kitchen area and rear bedroom give directly onto the private garden and large oak gazebo.",
    information: {
      facilities: [
        "All en-suite bedrooms (Air-conditioning to 1st floor)",
        "High quality cotton bedding with goose feather pillows (made up when you arrive)",
        "Shower products (shampoo/bodywash) provided in all bathrooms",
        "Welcome pack to get you up and running",
        "Dining table for up to eight",
        "International power adapters",
        "Underfloor heating (and cooling) throughout ground floor",
        "Super-king or queen sized beds",
        "43”/108cm flat-screen TV/DVD with internet/international channels",
        "WiFi (Inside and in the garden)",
        "Pool towels provided",
      ],
      suites: [
        {
          theme: "Animal magic theme",
          facilities: [
            "1st floor / 31m2",
            "Super-king / 180cm bed",
            "Air-conditioned",
            "43”/108cm flat-screen TV with internet/international channels",
            "High-quality duvet, pillows and bed linen",
            "Oak furniture including wardrobe, chest of drawers and bedside cabinets",
            "Clock radio with wireless/wired charging/USB",
            "Jack'n'Jill sink unit with lots of storage",
            "Large walk-in shower with wall-mounted shampoo/body-wash dispensers",
            "Illuminated magnifying mirror",
            "Hairdryer",
            "Separate toilet",
            "Velux window to watch the stars with electric blind",
          ],
        },
        {
          theme: "Modern Chic Theme",
          information:
            "This room has been adapted for disabled use as far as possible within the bounds of the existing building.  The Barn’s garden is accessed via a ramp and a ramp is available for access to the main door.",
          facilities: [
            "Ground floor / 21m2",
            "Queen / 160cm bed",
            "Underfloor heating (and cooling)",
            "High-quality duvet, pillows and bed linen",
            "Solid oak bedroom furniture",
            "Clock radion with wireless/wired charging/USB",
            "Blackout curtains",
            "Hairdryer",
            "90cm wide doors with lowered handles",
            "Grab handles for shower and toilet",
            "Folding shower screen",
            "Shower seat available",
            "Double sink unit with lots of storage",
            "Large heated and illuminated mirror",
            "Large, walk-in wet room shower with wall-mounted shampoo/body-wash dispensers",
          ],
        },
        {
          theme: "French Romantic Theme",
          facilities: [
            "Ground floor / 13m2",
            "Queen / 160cm bed",
            "Underfloor heating (and cooling)",
            "High-quality duvet, pillows and bed linen",
            "Solid oak wardrobe, chest of drawers, bedside tables",
            "Clock radio with wireless/wired charging/USB",
            "Blackout curtains",
            "Hairdryer",
            "Direct access to the garden",
            "Double sink unit with lots of storage",
            "Large, walk-in wet room shower with wall-mounted shampoo/body-wash dispensers",
            "Large, heated and illuminated mirror",
          ],
        },
      ],
      kitchen: {
        information:
          "The Barn is fitted with a custom kitchen constructed in solid wood and granite.  It is very well equipped with quality appliances and all the necessities for your stay including:",
        facilities: [
          "Range cooker with extractor hood",
          "Dishwasher",
          "Fridge/Freezer with water dispenser",
          "Espresso maker",
          "Kettle",
          "Microwave",
          "Electric whisk/blender",
          "Electric juice maker",
          "Cafetiere",
          "Toaster",
          "A wide selection of cutlery, glasses, utensils and Denby crockery",
          "A Washer/dryer is available in a separate laundry area",
        ],
      },
      garden: [
        "Landscaped garden with night time mood lighting",
        "Private, heated, Salt water plunge pool",
        "Gazebo with elegant dining table and chairs/cushions (for 8).  Remote control mood/dining lighting",
        "Terrace/sunbathing area with chaises longues/cushions",
        "Barbeque",
        "Views to the forest and stunning sunsets to the west!",
      ],
    },
    images: ["barn-bedroom-area", "barn-bedroom-area-2", "barn-bedroom-area-3", "barn-bedroom-area-4"],
  },
};

export default async function getGites(req, res) {
  res.status(200).json(gites);
}
